---
- name: enable audioctl
  service:
    name: fosdem-audioctl
    enabled: true
    state: restarted

- name: install nginx config for interface
  copy:
    src: nginx/interface.conf
    dest: /etc/nginx/sites-enabled/interface.conf
  register: nginx_config
