---
- name: enable audioctl
  service:
    name: fosdem-audioctl
    enabled: true
    state: restarted

- name: install nginx config for interface
  copy:
    src: nginx/interface.conf
    dest: /etc/nginx/sites-enabled/interface.conf
  notify: reload nginx

- name: remove default config
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: install very complex gui start page
  copy:
    src: nginx/index.html
    dest: /var/www/html/index.html
